### ISSUE TITLE
Terminal Resizing

### ISSUE THREAD

**Issue by lakefox** [sigmaSd/deno-pty-ffi#1]
Is it possible to resize the terminal once it is created?

**Comment by sigmaSd** [comment]
Not currently but it should be simple to expose more apis https://docs.rs/portable-pty/latest/portable_pty/trait.MasterPty.html#tymethod.resize

**Comment by sigmaSd** [comment]
Added in `0.15.1`

you can now use it like this

```ts
import { Pty } from "https://deno.land/x/deno_pty_ffi@0.15.1/mod.ts";

const pty = await Pty.create({
  cmd: "bash",
  args: [],
  env: [],
});

await pty.write("ls -la\n");
console.log(await pty.read());
console.log(pty.getSize()); //new
console.log(pty.resize({ //new
  rows: 20,
  cols: 10,
  pixel_height: 0,
  pixel_width: 0,
}));
console.log(pty.getSize()); //new
await pty.write("ls -la\n");
console.log(await pty.read());
```

**Comment by lakefox** [comment]
Thank you! That works perfectly, note to anyone who references this issue in the future, you must call `getSize()` before you can call the `resize` function.

**Comment by sigmaSd** [comment]
>you must call getSize() before you can call the resize function.

It shouldn't be, if that's the case it's a bug

**Comment by lakefox** [comment]
> > you must call getSize() before you can call the resize function.
> 
> It shouldn't be, if that's the case it's a bug

After testing it again it is working correctly, no need to add it before.
