### ISSUE TITLE
How to close the pty process?

### ISSUE THREAD

**Issue by imzlh** [sigmaSd/deno-pty-ffi#3]
I carefully searched through the code but couldn't find the way to close or simply send a signal to the process.
Would you tell me how to do?

**Comment by sigmaSd** [comment]
I added `close` api to 0.19.0 can you confirm that works for you ?

**Comment by imzlh** [comment]
![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/af4e7608-aa59-44ec-b35d-f34584be2f24)

I think you should change the version...

![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/0cc3660a-d076-4017-a14a-1baa38ec2f5e)

**Comment by imzlh** [comment]
And I think it will be better to trigger an Event when the process exits.Or simply by adding a getter function;
Thank you for your work!

**Comment by sigmaSd** [comment]
Good catch , unfortunately  I can't fix neither yank 0.19.0 version, so I uploaded 0.19.1 with the hotfix

**Comment by imzlh** [comment]
I find a hard problem.The program is stuck waiting for the write() function
The promise not come resolved or rejected.I cant find the reason.Please help me!

![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/d2d11c04-aba1-499c-83e8-0a891950c8ab)
![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/b9f69c17-4185-4782-8b91-eaae72804066)

And worse still,after calling close(),"Process exited with code 3221225477"

**Comment by sigmaSd** [comment]
Is the code open source? I can try to debug when I have time, windows is always tricky , though the ci passes these days

**Comment by imzlh** [comment]
Ehh...There still remains lots of bug and TODOs...
Here is a preview pack.Thank you a lot .(entry: front/main.ts)

[Code.zip](https://github.com/sigmaSd/deno-pty-ffi/files/14238558/Code.zip)

**Comment by sigmaSd** [comment]
no idea how to go past the login page, how do I reproduce the issue ?, also can you minimize the code responsible for the issues so I don't have to debug the whole project

From a quick glance I see you might be creating more then one pty (with each socket connection)  ?, if that's the case I think this is not currently supported

**Comment by sigmaSd** [comment]
>From a quick glance I see you might be creating more then one pty (with each socket connection) ?, if that's the case I think this is not currently supported

I pushed version 0.19.2 that fixes this, now different ptys can be spawned even together in theory

**Comment by sigmaSd** [comment]
I'm going to revert the changes I did, and take a step back because the windows issue is related to https://github.com/wez/wezterm/issues/4206
Basicly dropping the salve will just confuse windows

What do you expect of the close api, do you just want to close the spawned process ?

**Comment by sigmaSd** [comment]
I pushed 0.19.4 with the close api reworked to only close the spawned process, maybe give it a try and see if that improves the situation

**Comment by imzlh** [comment]
Did you publish the version yet? 

![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/1df8e1f0-1968-4846-9b72-763e689266df)

![image](https://github.com/sigmaSd/deno-pty-ffi/assets/114276136/eafcf858-a872-4641-b2c7-0d130cc21da7)

**Comment by sigmaSd** [comment]
I published it but it wasn't picked up by denoland, for some reason, I published 0.19.5  and I checked its available now

**Comment by imzlh** [comment]
Sorry,error happened still.
I give up...Thank you for your hard work.

I found that after around 2 second, I cannot writeIn any data.
But in test.ts，everything turn out great

**Comment by sigmaSd** [comment]
That's unfortunate, I opened https://github.com/sigmaSd/deno-pty-ffi/issues/4 to keep try to investigate windows issues more when I have time

Does the library work correctly (as in writes still works) if you don't use the close api ?

**Comment by imzlh** [comment]
No.
After 2s,the HTTP module seemed to be stopped, will never handle a new request.
I think that's why the strange problem occur.
But the eventloop is still working normally.

And I am using Windows10

**Comment by imzlh** [comment]
```ts
import { Pty } from "https://deno.land/x/deno_pty_ffi@0.19.1/mod.ts";

const socket = Deno.listen({
    port: 6666,
    hostname: 'localhost'
});

while (true) {
    const client = await socket.accept();
    if (!client) continue;
    const pty = new Pty({
        cmd: "cmd",
        args: [],
        env: [],
    }),
        encoder = new TextEncoder(),
        decoder = new TextDecoderStream();

    setInterval(() => pty.read().then(data => client.write(encoder.encode(data))), 100);

    (async function () {
        client.readable.pipeTo(decoder.writable);
        const reader = decoder.readable.getReader();
        while (true) {
            const data = await reader.read();
            if (data.done) return;
            if (data.value)
                pty.write(data.value);
        }
    })();
}
```
Try to run this code ,and telnet localhost 6666,the problem happned.

**Comment by sigmaSd** [comment]
Thanks for the reproduction code, that's definitely going to be helpful

**Comment by sigmaSd** [comment]
Testing that code on linux, the pty.read call doesn't give any result after a while,  I inverstiagted and read was blocking internanlly  , and for somereason when there are a lot of blocking reads it stops after a while (I couldn't quite figure this part yet)
I changed the pty read api to be non blocking, this needed some reworking of the api and pushed 0.19.6, here is the updated code snippet can you give it a test and see if that fixes the issue on windows

```ts
import { Pty } from "https://deno.land/x/deno_pty_ffi@0.19.6/mod.ts";

const socket = Deno.listen({
  port: 6666,
  hostname: "localhost",
});

while (true) {
  const client = await socket.accept();
  if (!client) continue;
  const pty = new Pty({
      cmd: "fish",
      args: [],
      env: [],
    }),
    encoder = new TextEncoder(),
    decoder = new TextDecoderStream();

  setInterval(
    () =>
      pty.read().then(({ data, done }) => {
        if (data) {
          console.log(data);
          client.write(encoder.encode(data));
        }
      }),
    100,
  );

  (async function () {
    client.readable.pipeTo(decoder.writable);
    const reader = decoder.readable.getReader();
    while (true) {
      const data = await reader.read();
      if (data.done) return;
      if (data.value) {
        pty.write(data.value);
      }
    }
  })();
}
```

**Comment by imzlh** [comment]
It worked out fine on Windows!Thank you a lot

**Comment by sigmaSd** [comment]
If you have other issues feel free to open new ones
